// 文件功能：Gradle 模块配置——Android library（AAR）。
// 通过 ndkBuild 编译 tinywrapper 原生代码（仅 arm64-v8a），
// 供启动器（FCL/Pojav 等）以渲染器插件方式加载。
plugins {
    id 'com.android.library'
}

android {
    namespace "git.artdeell.ltw"
    compileSdk 33
    defaultConfig {
        minSdk 21
        ndk {
            abiFilters "arm64-v8a"
        }
        externalNativeBuild {
            ndkBuild {
                arguments '-j24'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    ndkVersion = "28.2.13676358"
    externalNativeBuild {
        ndkBuild {
            path file('src/main/tinywrapper/Android.mk')
        }
    }
}

dependencies {
}
